### ISSUE TITLE
Errors after changing modID, author and steam path

### ISSUE THREAD

**Issue by Ljintao** [Alchyr/BasicMod#11]
<img width="1429" alt="屏幕截图 2024-11-02 152857" src="https://github.com/user-attachments/assets/95cc5ec5-c099-4472-99d0-a6eacd44bb58">
After I change modID, author and steam path, there are still errors.

**Comment by Alchyr** [comment]
Unfortunately, this is an issue with intelliJ failing to download the referenced plugins correctly, and there isn't much I can do about it. It could be caused by a temporary outage, firewalls, or many other things. It might fix itself if you try again later, or it might not. While the json validator plugin could be removed from the pom.xml file without much issue, the maven-resources plugin cannot.
